//! Bestow export: turn a wright island document into exactly the files the
//! engine consumes today (see bestow `games/isles/assets/islands/` and
//! `bestow-runtime/src/terrain.rs`):
//!
//! - `<name>.hgt.png` — 16-bit grayscale heightmap, normalized over
//!   `[height_min, height_max]`
//! - `<name>.hgt.toml` — placement metadata (grid + world extents)
//! - `<name>.ctl.png` — control mask (R = rockness, G = autoshader)
//! - `<name>.color.png` — RGB tint
//! - `<file>.import.toml` — UUIDv7 sidecar for every file written (bestow
//!   D-011: asset identity survives renames)
//! - `<name>.entity.toml` — ready-to-paste scene entity (render + terrain
//!   components) wired to the files above
//!
//! Writers are atomic-ish (write to `.tmp`, rename) so a running bestow
//! watching the assets dir never half-reads a file mid-hot-reload.

use anyhow::{Context, Result};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use wright_field::{Heightfield, Masks};

pub struct ExportOptions {
    /// Island name — becomes the file stem and the scene entity name.
    pub name: String,
    /// Asset directory to write into, e.g. `<game>/assets/islands`.
    pub out_dir: PathBuf,
    /// Asset path prefix as the *scene* will reference it, e.g.
    /// `assets/islands` (bestow asset paths are game-root-relative).
    pub asset_prefix: String,
    /// Shader + detail textures for the entity snippet. Defaults match the
    /// isles game's baked island look.
    pub shader: String,
    pub grass_texture: String,
    pub rock_texture: String,
}

impl ExportOptions {
    pub fn new(name: &str, out_dir: impl Into<PathBuf>) -> Self {
        Self {
            name: name.to_string(),
            out_dir: out_dir.into(),
            asset_prefix: "assets/islands".to_string(),
            shader: "shaders/island_baked.slang".to_string(),
            grass_texture: "assets/islands/grass.png".to_string(),
            rock_texture: "assets/islands/rock.png".to_string(),
        }
    }
}

/// Everything an export produced, for the UI to report.
pub struct ExportReport {
    pub files: Vec<PathBuf>,
    pub height_min: f32,
    pub height_max: f32,
    pub entity_toml: String,
}

pub fn export_island(
    field: &Heightfield,
    masks: &Masks,
    opts: &ExportOptions,
) -> Result<ExportReport> {
    fs::create_dir_all(&opts.out_dir)
        .with_context(|| format!("creating {}", opts.out_dir.display()))?;

    let (height_min, mut height_max) = field.min_max();
    if height_max - height_min < 1e-3 {
        // dead-flat island: keep the window non-degenerate so the PNG
        // normalization and bestow's remap stay well-defined
        height_max = height_min + 1.0;
    }

    let res = field.resolution() as u32;
    let mut files = Vec::new();

    // ── heightmap: 16-bit grayscale, row-major from -Z corner ────────────
    let range = height_max - height_min;
    let hgt: Vec<u16> = field
        .heights()
        .iter()
        .map(|&h| (((h - height_min) / range).clamp(0.0, 1.0) * 65535.0).round() as u16)
        .collect();
    let hgt_path = opts.out_dir.join(format!("{}.hgt.png", opts.name));
    write_png16(&hgt_path, res, res, &hgt)?;
    files.push(hgt_path.clone());

    // ── placement metadata (matches scripts/argh_dump_terrain.py output) ─
    let origin = field.world_origin();
    let meta = format!(
        "# Generated by wright — placement metadata for {name}.hgt.png\n\
         # (16-bit grayscale heightfield).\n\n\
         width = {res}\n\
         height = {res}\n\
         world_origin_x = {ox}\n\
         world_origin_z = {oz}\n\
         world_size_x = {size}\n\
         world_size_z = {size}\n\
         height_min = {hmin}\n\
         height_max = {hmax}\n",
        name = opts.name,
        ox = origin.x,
        oz = origin.y,
        size = field.world_size(),
        hmin = height_min,
        hmax = height_max,
    );
    let meta_path = opts.out_dir.join(format!("{}.hgt.toml", opts.name));
    write_atomic(&meta_path, meta.as_bytes())?;
    files.push(meta_path);

    // ── control mask: R = rockness, G = autoshader ────────────────────────
    let mut ctl = Vec::with_capacity((res * res * 3) as usize);
    for i in 0..(res * res) as usize {
        ctl.push(masks.rockness[i]);
        ctl.push(masks.autoshader[i]);
        ctl.push(0);
    }
    let ctl_path = opts.out_dir.join(format!("{}.ctl.png", opts.name));
    write_png_rgb8(&ctl_path, res, res, &ctl)?;
    files.push(ctl_path);

    // ── color tint ────────────────────────────────────────────────────────
    let mut color = Vec::with_capacity((res * res * 3) as usize);
    for t in &masks.tint {
        color.extend_from_slice(t);
    }
    let color_path = opts.out_dir.join(format!("{}.color.png", opts.name));
    write_png_rgb8(&color_path, res, res, &color)?;
    files.push(color_path);

    // ── scene entity snippet ──────────────────────────────────────────────
    let entity_toml = entity_snippet(field, opts, height_min, height_max);
    let entity_path = opts.out_dir.join(format!("{}.entity.toml", opts.name));
    write_atomic(&entity_path, entity_toml.as_bytes())?;
    files.push(entity_path);

    // ── UUIDv7 sidecars for everything written ───────────────────────────
    for f in files.clone() {
        let sidecar = sidecar_path(&f);
        if !sidecar.exists() {
            // never regenerate an id for an asset bestow may already track
            write_atomic(
                &sidecar,
                format!("id = \"{}\"\n", uuid::Uuid::now_v7()).as_bytes(),
            )?;
        }
        files.push(sidecar);
    }

    Ok(ExportReport {
        files,
        height_min,
        height_max,
        entity_toml,
    })
}

fn sidecar_path(file: &Path) -> PathBuf {
    let mut s = file.as_os_str().to_os_string();
    s.push(".import.toml");
    PathBuf::from(s)
}

fn entity_snippet(
    field: &Heightfield,
    opts: &ExportOptions,
    height_min: f32,
    height_max: f32,
) -> String {
    let mut s = String::new();
    let name = &opts.name;
    let prefix = &opts.asset_prefix;
    let _ = writeln!(
        s,
        "# Paste into a scene to place `{name}` (exported by wright)."
    );
    let _ = writeln!(s, "[[entities]]");
    let _ = writeln!(s, "name = \"{name}\"");
    let _ = writeln!(s, "[entities.components.transform]");
    let _ = writeln!(s, "position = [0.0, 0.0, 0.0]");
    let _ = writeln!(s, "[entities.components.render]");
    let _ = writeln!(s, "model = \"terrain\"");
    let _ = writeln!(s, "shader = \"{}\"", opts.shader);
    let _ = writeln!(s, "texture = \"{prefix}/{name}.ctl.png\"");
    let _ = writeln!(s, "texture2 = \"{}\"", opts.grass_texture);
    let _ = writeln!(s, "texture3 = \"{}\"", opts.rock_texture);
    let _ = writeln!(s, "color = [1.0, 1.0, 1.0, 1.0]");
    let _ = writeln!(s, "[entities.components.terrain]");
    let _ = writeln!(s, "heightmap = \"{prefix}/{name}.hgt.png\"");
    let _ = writeln!(s, "size = {:.1}", field.world_size());
    let _ = writeln!(s, "height_min = {height_min}");
    let _ = writeln!(s, "height_max = {height_max}");
    let _ = writeln!(s, "resolution = {}", field.resolution().min(1024));
    s
}

fn write_atomic(path: &Path, bytes: &[u8]) -> Result<()> {
    let tmp = path.with_extension("tmp~");
    fs::write(&tmp, bytes).with_context(|| format!("writing {}", tmp.display()))?;
    fs::rename(&tmp, path).with_context(|| format!("renaming into {}", path.display()))?;
    Ok(())
}

fn write_png16(path: &Path, w: u32, h: u32, data: &[u16]) -> Result<()> {
    let mut bytes = Vec::with_capacity(data.len() * 2);
    for &v in data {
        bytes.extend_from_slice(&v.to_be_bytes()); // PNG is big-endian
    }
    write_png(
        path,
        w,
        h,
        png::ColorType::Grayscale,
        png::BitDepth::Sixteen,
        &bytes,
    )
}

fn write_png_rgb8(path: &Path, w: u32, h: u32, data: &[u8]) -> Result<()> {
    write_png(path, w, h, png::ColorType::Rgb, png::BitDepth::Eight, data)
}

fn write_png(
    path: &Path,
    w: u32,
    h: u32,
    color: png::ColorType,
    depth: png::BitDepth,
    bytes: &[u8],
) -> Result<()> {
    let tmp = path.with_extension("tmp~");
    {
        let file = fs::File::create(&tmp).with_context(|| format!("creating {}", tmp.display()))?;
        let mut enc = png::Encoder::new(std::io::BufWriter::new(file), w, h);
        enc.set_color(color);
        enc.set_depth(depth);
        let mut writer = enc.write_header()?;
        writer.write_image_data(bytes)?;
    }
    fs::rename(&tmp, path).with_context(|| format!("renaming into {}", path.display()))?;
    Ok(())
}

/// Decode a 16-bit grayscale PNG back to normalized heights — used by tests
/// and by project import of existing bestow islands.
pub fn read_png16(path: &Path) -> Result<(Vec<f32>, u32, u32)> {
    let decoder = png::Decoder::new(std::io::BufReader::new(fs::File::open(path)?));
    let mut reader = decoder.read_info()?;
    let mut buf = vec![0u8; reader.output_buffer_size().context("png too large")?];
    let info = reader.next_frame(&mut buf)?;
    anyhow::ensure!(
        info.color_type == png::ColorType::Grayscale && info.bit_depth == png::BitDepth::Sixteen,
        "expected 16-bit grayscale, got {:?}/{:?}",
        info.color_type,
        info.bit_depth
    );
    let samples = buf[..info.buffer_size()]
        .chunks_exact(2)
        .map(|c| u16::from_be_bytes([c[0], c[1]]) as f32 / 65535.0)
        .collect();
    Ok((samples, info.width, info.height))
}

#[cfg(test)]
mod tests {
    use super::*;
    use wright_field::{Brush, BrushKind, Stroke};

    fn sculpted() -> (Heightfield, Masks) {
        let mut f = Heightfield::new(65, 64.0, -5.0);
        let mut m = Masks::new(65);
        let mut s = Stroke::new(
            Brush {
                kind: BrushKind::Raise,
                radius: 20.0,
                strength: 18.0,
                ..Default::default()
            },
            0.0,
        );
        s.apply(&mut f, &mut m, 0.0, 0.0, 1.0);
        (f, m)
    }

    #[test]
    fn export_writes_full_file_set_with_sidecars() {
        let (f, m) = sculpted();
        let dir = tempfile::tempdir().unwrap();
        let report = export_island(&f, &m, &ExportOptions::new("testle", dir.path())).unwrap();
        for stem in [
            "testle.hgt.png",
            "testle.hgt.toml",
            "testle.ctl.png",
            "testle.color.png",
            "testle.entity.toml",
        ] {
            let p = dir.path().join(stem);
            assert!(p.exists(), "missing {stem}");
            assert!(sidecar_path(&p).exists(), "missing sidecar for {stem}");
        }
        assert!(
            report
                .entity_toml
                .contains("heightmap = \"assets/islands/testle.hgt.png\"")
        );
        assert!(report.entity_toml.contains("model = \"terrain\""));
    }

    #[test]
    fn heightmap_roundtrips_through_png16() {
        let (f, m) = sculpted();
        let dir = tempfile::tempdir().unwrap();
        let report = export_island(&f, &m, &ExportOptions::new("rt", dir.path())).unwrap();
        let (norm, w, h) = read_png16(&dir.path().join("rt.hgt.png")).unwrap();
        assert_eq!((w, h), (65, 65));
        let range = report.height_max - report.height_min;
        for (i, &n) in norm.iter().enumerate() {
            let decoded = report.height_min + n * range;
            let expected = f.heights()[i];
            assert!(
                (decoded - expected).abs() < range / 65535.0 * 2.0,
                "sample {i}: {decoded} vs {expected}"
            );
        }
    }

    #[test]
    fn sidecar_ids_are_stable_across_reexport() {
        let (f, m) = sculpted();
        let dir = tempfile::tempdir().unwrap();
        let opts = ExportOptions::new("stable", dir.path());
        export_island(&f, &m, &opts).unwrap();
        let sc = dir.path().join("stable.hgt.png.import.toml");
        let first = fs::read_to_string(&sc).unwrap();
        export_island(&f, &m, &opts).unwrap();
        assert_eq!(
            first,
            fs::read_to_string(&sc).unwrap(),
            "uuid must not churn"
        );
    }

    #[test]
    fn flat_island_exports_nondegenerate_range() {
        let f = Heightfield::new(8, 8.0, 2.0);
        let m = Masks::new(8);
        let dir = tempfile::tempdir().unwrap();
        let r = export_island(&f, &m, &ExportOptions::new("flat", dir.path())).unwrap();
        assert!(r.height_max > r.height_min);
    }
}
