//! Export a dungeon as ONE self-contained bestow asset folder:
//!
//! ```text
//! assets/dungeons/<name>/
//!   <name>.scene.toml        # the playable scene (sky + shell + doors + entities)
//!   <name>.shell.glb         # walls/floors/ceilings, visual AND collision
//!   templates/door.template.toml
//!   *.import.toml            # UUIDv7 sidecars for every file
//! ```
//!
//! Drop the folder into a game's `assets/` and play it:
//! `scene.load("assets/dungeons/<name>/<name>.scene.toml")`. The shell
//! entity uses bestow's `physics { shape = "mesh" }` trimesh collider; the
//! engine cooks collision from the same glb it renders. Locked/boss doors
//! export as blocking slab entities (path-qualified template, no global
//! name collisions); open doorways export as marker entities so nothing
//! blocks them by default. Gameplay (opening doors, granting keys) stays
//! in the game's Lua — wright exports data, never behavior.

use crate::{DoorKind, DungeonDoc, glb, meshgen};
use anyhow::{Context, Result};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// Files an export produced, for the UI to report.
pub struct ExportReport {
    pub files: Vec<PathBuf>,
    pub scene_rel: String,
    pub triangle_count: usize,
    /// Validation issues found at export time (export proceeds on
    /// warnings; errors abort before any file is written).
    pub warnings: Vec<String>,
}

/// Escape a string for a TOML basic (double-quoted) string — user-entered
/// names/tags/keys must never corrupt the exported scene.
fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

pub(crate) fn write_sidecar(file: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    let mut s = file.as_os_str().to_os_string();
    s.push(".import.toml");
    let sidecar = PathBuf::from(s);
    if !sidecar.exists() {
        std::fs::write(&sidecar, format!("id = \"{}\"\n", uuid::Uuid::now_v7()))
            .with_context(|| format!("writing {}", sidecar.display()))?;
    }
    files.push(sidecar);
    Ok(())
}

/// Export into `<dungeons_dir>/<name>/`. `asset_prefix` is how the game
/// will reference the folder (e.g. `assets/dungeons`), so the scene's
/// internal paths come out as `assets/dungeons/<name>/...`.
pub fn export_dungeon(
    doc: &DungeonDoc,
    dungeons_dir: &Path,
    asset_prefix: &str,
) -> Result<ExportReport> {
    let issues = doc.validate();
    if let Some(err) = issues.iter().find(|i| i.error) {
        anyhow::bail!("dungeon invalid: {}", err.message);
    }
    let warnings: Vec<String> = issues.into_iter().map(|i| i.message).collect();

    let name = sanitize(&doc.name);
    let dir = dungeons_dir.join(&name);
    let prefix = format!("{}/{name}", asset_prefix.trim_end_matches('/'));
    fs::create_dir_all(dir.join("templates"))
        .with_context(|| format!("creating {}", dir.display()))?;

    let mut files = Vec::new();

    // ── shell mesh ────────────────────────────────────────────────────────
    let mesh = meshgen::generate(doc);
    let shell_path = dir.join(format!("{name}.shell.glb"));
    glb::write_glb(&shell_path, &name, &mesh)?;
    files.push(shell_path.clone());

    // ── door template (sized to this dungeon's doorways) ─────────────────
    let (dw, dh) = doc.door_dims();
    let door_tpl = format!(
        "# Blocking door slab for `{name}` (generated by wright).\n\
         # The game opens it: despawn / move / animate on unlock.\n\
         [template]\n\
         name = \"{name}/door\"\n\
         tags = [\"door\"]\n\n\
         [components.render]\n\
         model = \"primitive:cube\"\n\
         color = [0.42, 0.28, 0.15, 1.0]\n\n\
         [components.transform]\n\
         scale = [{sx}, {sy}, 0.22]\n\n\
         [components.physics]\n\
         body = \"static\"\n\
         shape = \"box\"\n\
         half_extents = [{hx}, {hy}, 0.11]\n",
        sx = dw,
        sy = dh,
        hx = dw * 0.5,
        hy = dh * 0.5,
    );
    let door_tpl_path = dir.join("templates/door.template.toml");
    fs::write(&door_tpl_path, door_tpl)?;
    files.push(door_tpl_path);
    let door_tpl_rel = format!("{prefix}/templates/door.template.toml");

    // ── scene ─────────────────────────────────────────────────────────────
    let mut s = String::new();
    let _ = writeln!(
        s,
        "# Dungeon `{name}` — exported by wright as a self-contained asset folder.\n\
         # Play it:   scene.load(\"{prefix}/{name}.scene.toml\")\n\
         # Spawn at:  the entity tagged `player_spawn`.\n\
         # Doors:     locked/boss doors are blocking slabs tagged door.locked/door.boss\n\
         #            (+ key.<id>); open doorways are markers tagged door.open.\n"
    );

    // dim cavern sky so the dungeon doesn't inherit a sunny overworld look
    let _ = writeln!(
        s,
        "[[entities]]\nname = \"sky\"\n[entities.components.sky]\n\
         horizon = [0.10, 0.09, 0.085]\n\
         zenith = [0.035, 0.035, 0.045]\n\
         sun_dir = [0.25, 0.8, 0.3]\n\
         sun_color = [0.30, 0.28, 0.25]\n\
         sun_size = 0.02\n"
    );

    let _ = writeln!(
        s,
        "[[entities]]\nname = \"shell\"\n\
         [entities.components.transform]\nposition = [0.0, 0.0, 0.0]\n\
         [entities.components.render]\nmodel = \"{prefix}/{name}.shell.glb\"\n\
         [entities.components.physics]\nbody = \"static\"\nshape = \"mesh\"\nfriction = 0.9\n"
    );

    for door in &doc.doors {
        let base_y = door.floor as f32 * doc.floor_height;
        let ca = doc.cell_center(door.floor, door.a.0, door.a.1);
        let cb = doc.cell_center(door.floor, door.b.0, door.b.1);
        let (ex, ez) = ((ca[0] + cb[0]) * 0.5, (ca[2] + cb[2]) * 0.5);
        // slab is thin along Z at yaw 0 → doors crossing Z stay at 0,
        // doors crossing X turn 90°. bestow transform.rotation = Euler XYZ
        // radians (world.rs local_transform), not a quaternion.
        let crossing_x = door.a.0 != door.b.0;
        let yaw = if crossing_x {
            std::f32::consts::FRAC_PI_2
        } else {
            0.0
        };
        let mut tags = vec!["door".to_string(), format!("door.{}", door.kind.label())];
        if let DoorKind::Locked { key } = &door.kind {
            tags.push(format!("key.{key}")); // esc happens at serialization below
        }
        let tags_toml = tags
            .iter()
            .map(|t| format!("\"{}\"", esc(t)))
            .collect::<Vec<_>>()
            .join(", ");

        let _ = writeln!(s, "[[entities]]");
        let _ = writeln!(s, "name = \"{}\"", esc(&door.name));
        if door.kind != DoorKind::Open {
            let _ = writeln!(s, "template = \"{door_tpl_rel}\"");
        }
        let _ = writeln!(s, "tags = [{tags_toml}]");
        let _ = writeln!(s, "[entities.components.transform]");
        let _ = writeln!(s, "position = [{ex}, {y}, {ez}]", y = base_y + dh * 0.5);
        let _ = writeln!(s, "rotation = [0.0, {yaw}, 0.0]\n");
    }

    for e in &doc.entities {
        let _ = writeln!(s, "[[entities]]");
        if !e.name.is_empty() {
            let _ = writeln!(s, "name = \"{}\"", esc(&e.name));
        }
        if !e.template.is_empty() {
            let _ = writeln!(s, "template = \"{}\"", esc(&e.template));
        }
        if !e.tags.is_empty() {
            let tags = e
                .tags
                .iter()
                .map(|t| format!("\"{}\"", esc(t)))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(s, "tags = [{tags}]");
        }
        let _ = writeln!(s, "[entities.components.transform]");
        let _ = writeln!(
            s,
            "position = [{}, {}, {}]",
            e.position[0], e.position[1], e.position[2]
        );
        if e.yaw_deg.abs() > 1e-3 {
            let _ = writeln!(s, "rotation = [0.0, {}, 0.0]", e.yaw_deg.to_radians());
        }
        let _ = writeln!(s);
    }

    let scene_path = dir.join(format!("{name}.scene.toml"));
    fs::write(&scene_path, s)?;
    files.push(scene_path);

    for f in files.clone() {
        write_sidecar(&f, &mut files)?;
    }

    Ok(ExportReport {
        files,
        scene_rel: format!("{prefix}/{name}.scene.toml"),
        triangle_count: mesh.triangle_count(),
        warnings,
    })
}

fn sanitize(name: &str) -> String {
    let s: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    if s.is_empty() { "dungeon".into() } else { s }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Cell, Door, DungeonEntity};

    fn dungeon() -> DungeonDoc {
        let mut doc = DungeonDoc::new("Fire Temple", 9, 3);
        let f = &mut doc.floors[0];
        for z in 0..3 {
            for x in 0..3 {
                f.set(x, z, Cell::Floor);
                f.set(x + 6, z, Cell::Floor);
            }
        }
        for x in 3..6 {
            f.set(x, 1, Cell::Floor);
        }
        doc.doors.push(Door {
            name: "east_door".into(),
            floor: 0,
            a: (4, 1),
            b: (5, 1),
            kind: DoorKind::Locked {
                key: "small_key".into(),
            },
        });
        doc.doors.push(Door {
            name: "west_arch".into(),
            floor: 0,
            a: (3, 1),
            b: (4, 1),
            kind: DoorKind::Open,
        });
        doc.entities.push(DungeonEntity {
            name: "spawn".into(),
            template: String::new(),
            tags: vec!["player_spawn".into()],
            position: doc.cell_center(0, 1, 1),
            yaw_deg: 90.0,
        });
        doc.entities.push(DungeonEntity {
            name: "key1".into(),
            template: "chest".into(),
            tags: vec!["key.small_key".into()],
            position: doc.cell_center(0, 7, 1),
            yaw_deg: 0.0,
        });
        doc
    }

    #[test]
    fn export_produces_folder_scene_and_sidecars() {
        let dir = tempfile::tempdir().unwrap();
        let report = export_dungeon(&dungeon(), dir.path(), "assets/dungeons").unwrap();
        assert!(report.warnings.is_empty(), "{:?}", report.warnings);
        assert_eq!(
            report.scene_rel,
            "assets/dungeons/fire_temple/fire_temple.scene.toml"
        );

        let folder = dir.path().join("fire_temple");
        for rel in [
            "fire_temple.scene.toml",
            "fire_temple.shell.glb",
            "templates/door.template.toml",
        ] {
            let p = folder.join(rel);
            assert!(p.exists(), "missing {rel}");
            let mut sc = p.as_os_str().to_os_string();
            sc.push(".import.toml");
            assert!(PathBuf::from(sc).exists(), "missing sidecar for {rel}");
        }
    }

    #[test]
    fn scene_toml_is_valid_and_complete() {
        let dir = tempfile::tempdir().unwrap();
        export_dungeon(&dungeon(), dir.path(), "assets/dungeons").unwrap();
        let scene_src =
            fs::read_to_string(dir.path().join("fire_temple/fire_temple.scene.toml")).unwrap();
        let v: toml::Value = toml::from_str(&scene_src).unwrap();
        let entities = v["entities"].as_array().unwrap();
        // sky + shell + 2 doors + 2 placed
        assert_eq!(entities.len(), 6);

        let by_name = |n: &str| {
            entities
                .iter()
                .find(|e| e.get("name").and_then(|v| v.as_str()) == Some(n))
                .unwrap_or_else(|| panic!("entity `{n}`"))
        };
        let shell = by_name("shell");
        assert_eq!(
            shell["components"]["render"]["model"].as_str(),
            Some("assets/dungeons/fire_temple/fire_temple.shell.glb")
        );
        assert_eq!(
            shell["components"]["physics"]["shape"].as_str(),
            Some("mesh")
        );

        // locked door: blocking template by path + key tag; rotated 90°
        // (its cells differ in x)
        let locked = by_name("east_door");
        assert_eq!(
            locked["template"].as_str(),
            Some("assets/dungeons/fire_temple/templates/door.template.toml")
        );
        let tags: Vec<&str> = locked["tags"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|t| t.as_str())
            .collect();
        assert!(tags.contains(&"door.locked") && tags.contains(&"key.small_key"));
        let rot = locked["components"]["transform"]["rotation"]
            .as_array()
            .unwrap();
        assert_eq!(rot.len(), 3, "Euler XYZ radians, not a quaternion");
        assert!((rot[1].as_float().unwrap() - std::f64::consts::FRAC_PI_2).abs() < 1e-3);

        // open doorway: marker only, no template
        let arch = by_name("west_arch");
        assert!(arch.get("template").is_none());

        // door template parses and matches bestow's template shape
        let tpl_src =
            fs::read_to_string(dir.path().join("fire_temple/templates/door.template.toml"))
                .unwrap();
        let tpl: toml::Value = toml::from_str(&tpl_src).unwrap();
        assert_eq!(tpl["template"]["name"].as_str(), Some("fire_temple/door"));
        assert_eq!(tpl["components"]["physics"]["shape"].as_str(), Some("box"));
    }

    #[test]
    fn export_refuses_invalid_dungeons() {
        let mut doc = dungeon();
        doc.doors.push(Door {
            name: "broken".into(),
            floor: 0,
            a: (0, 0),
            b: (5, 0),
            kind: DoorKind::Open,
        });
        let dir = tempfile::tempdir().unwrap();
        assert!(export_dungeon(&doc, dir.path(), "assets/dungeons").is_err());
    }
}
